.\" This is the manpage title!
.\" Contact https://github.com/filhoDaMain to ask for bug fixes
.TH HELLO "1" "February 2023" "hello 1.0" 
.SH NAME
hello
.SH SYNOPSIS
hello (with no arguments)
.SH DESCRIPTION
When called, hello will greet the user with a Hello World! message.
.SH AUTHORS
Andre Temprilho